### ISSUE TITLE
Not working in EE 5.0.6

### ISSUE THREAD

**Issue by nymo** [DSB/Oxid-Module-IDE-Helper#5]
Hi,
this module is not working in EE 5.0.6. The method getModules() in oxmodulelist does not exist. Could be a problem of the EE Version. I'm not sure then the getModules method was introduced by oxid.

**Comment by DSB** [comment]
Hi,
I don't use Oxid anymore. Please fix it yourself and create a pull request.

**Comment by nymo** [comment]
Since we updated to latest oxid version it is now working. We don't need the fix for 5.0.6 anymore.
